import { Routes } from '@angular/router';
import { authGuard, roleGuard } from '../../core/auth/auth.guard';

export const publicRoutes: Routes = [
  { path: '', title: 'ChezVoust Pro | Serviços domésticos com confiança', data: { seo: { title: 'ChezVoust Pro | Serviços domésticos com confiança', description: 'Encontre profissionais aprovados para cuidar da sua casa no dia e horário que você escolher.', canonicalPath: '/', structuredData: [{ '@context': 'https://schema.org', '@type': 'WebSite', name: 'ChezVoust Pro', url: '/', potentialAction: { '@type': 'SearchAction', target: '/servicos?q={search_term_string}', 'query-input': 'required name=search_term_string' } }, { '@context': 'https://schema.org', '@type': 'Organization', name: 'ChezVoust Pro', url: '/' }] } }, loadComponent: () => import('./pages/home/home.component').then((m) => m.HomeComponent) },
  { path: 'servicos', title: 'Serviços | ChezVoust Pro', data: { seo: { title: 'Serviços para casa | ChezVoust Pro', description: 'Encontre serviços para casa, compare opções e solicite um horário com profissionais aprovados.', canonicalPath: '/servicos' } }, loadComponent: () => import('./pages/catalog/catalog.component').then((m) => m.CatalogComponent) },
  { path: 'servicos/categoria/:category', title: 'Serviços por categoria | ChezVoust Pro', data: { seo: { title: 'Serviços para casa | ChezVoust Pro', description: 'Compare serviços para casa e escolha a opção que atende à sua rotina.', canonicalPath: '/servicos' } }, loadComponent: () => import('./pages/catalog/catalog.component').then((m) => m.CatalogComponent) },
  { path: 'servicos/:slug', title: 'Detalhes do serviço | ChezVoust Pro', data: { seo: { title: 'Detalhes do serviço | ChezVoust Pro', description: 'Confira os detalhes do serviço e solicite um horário com confiança.' } }, loadComponent: () => import('./pages/service-detail/service-detail.component').then((m) => m.ServiceDetailComponent) },
  { path: 'profissionais', title: 'Profissionais | ChezVoust Pro', data: { seo: { title: 'Profissionais para sua casa | ChezVoust Pro', description: 'Conheça profissionais aprovados, avaliações de reservas e experiências para contratar com segurança.', canonicalPath: '/profissionais' } }, loadComponent: () => import('./pages/professionals/professionals.component').then((m) => m.ProfessionalsComponent) },
  { path: 'profissionais/:id/:slug', title: 'Perfil profissional | ChezVoust Pro', data: { seo: { title: 'Perfil profissional | ChezVoust Pro', description: 'Conheça experiências, serviços e avaliações verificadas deste profissional.' } }, loadComponent: () => import('./pages/provider-detail/provider-detail.component').then((m) => m.ProviderDetailComponent) },
  { path: 'profissionais/:id', title: 'Perfil profissional | ChezVoust Pro', data: { seo: { title: 'Perfil profissional | ChezVoust Pro', description: 'Conheça experiências, serviços e avaliações verificadas deste profissional.' } }, loadComponent: () => import('./pages/provider-detail/provider-detail.component').then((m) => m.ProviderDetailComponent) },
  { path: 'agendar/:serviceId', title: 'Agendar serviço | ChezVoust Pro', canActivate: [authGuard, roleGuard('customer')], data: { seo: { noindex: true } }, loadComponent: () => import('../booking/pages/booking-wizard/booking-wizard.component').then((m) => m.BookingWizardComponent) },
  { path: 'como-funciona', title: 'Como funciona | ChezVoust Pro', data: { page: 'how', seo: { title: 'Como funciona | ChezVoust Pro', description: 'Entenda como encontrar, contratar e acompanhar serviços para a sua casa.', canonicalPath: '/como-funciona' } }, loadComponent: () => import('./pages/info/info-page.component').then((m) => m.InfoPageComponent) },
  { path: 'seguranca', title: 'Segurança | ChezVoust Pro', data: { page: 'safety', seo: { title: 'Segurança | ChezVoust Pro', description: 'Saiba como avaliações, perfis e comunicação pela plataforma ajudam na contratação.', canonicalPath: '/seguranca' } }, loadComponent: () => import('./pages/info/info-page.component').then((m) => m.InfoPageComponent) },
  { path: 'ajuda', title: 'Central de ajuda | ChezVoust Pro', data: { page: 'help', seo: { title: 'Central de ajuda | ChezVoust Pro', description: 'Encontre orientações para usar a ChezVoust Pro e acompanhar seus serviços.', canonicalPath: '/ajuda' } }, loadComponent: () => import('./pages/info/info-page.component').then((m) => m.InfoPageComponent) },
  { path: 'termos', title: 'Termos de uso | ChezVoust Pro', data: { page: 'terms', seo: { title: 'Termos de uso | ChezVoust Pro', description: 'Consulte as condições de uso da plataforma ChezVoust Pro.', canonicalPath: '/termos' } }, loadComponent: () => import('./pages/info/info-page.component').then((m) => m.InfoPageComponent) },
  { path: 'privacidade', title: 'Privacidade | ChezVoust Pro', data: { page: 'privacy', seo: { title: 'Privacidade | ChezVoust Pro', description: 'Conheça o aviso de privacidade e os dados utilizados pela plataforma.', canonicalPath: '/privacidade' } }, loadComponent: () => import('./pages/info/info-page.component').then((m) => m.InfoPageComponent) }
];
