import { DOCUMENT, registerLocaleData } from '@angular/common';
import { Injectable, computed, inject, signal } from '@angular/core';
import localeFr from '@angular/common/locales/fr';
import localePt from '@angular/common/locales/pt';

registerLocaleData(localePt);
registerLocaleData(localeFr);

export type AppLanguage = 'pt' | 'en' | 'fr';
export type AppCurrency = 'BRL' | 'EUR' | 'USD';

interface TranslationEntry {
  pt: string;
  en: string;
  fr: string;
}

const LANGUAGE_KEY = 'cvp.language';
const CURRENCY_KEY = 'cvp.currency';
// Todos os preços-base do catálogo usam centavos de real. As conversões são
// somente de exibição e não representam cobrança pela plataforma.
const USD_PER_BRL = 0.20;
const EUR_PER_BRL = 0.17;

const TRANSLATIONS: TranslationEntry[] = [
  { pt: 'Idioma', en: 'Language', fr: 'Langue' },
  { pt: 'Moeda', en: 'Currency', fr: 'Devise' },
  { pt: 'Preferências de idioma e moeda', en: 'Language and currency preferences', fr: 'Préférences de langue et de devise' },
  { pt: 'Preferências', en: 'Preferences', fr: 'Préférences' },
  { pt: 'Idioma e moeda', en: 'Language and currency', fr: 'Langue et devise' },
  { pt: 'Fechar preferências', en: 'Close preferences', fr: 'Fermer les préférences' },
  { pt: 'Inglês', en: 'English', fr: 'Anglais' },
  { pt: 'Francês', en: 'French', fr: 'Français' },
  { pt: 'Euro', en: 'Euro', fr: 'Euro' },
  { pt: 'Real brasileiro', en: 'Brazilian real', fr: 'Réal brésilien' },
  { pt: 'Dólar americano', en: 'US dollar', fr: 'Dollar américain' },
  { pt: 'Pular para o conteúdo', en: 'Skip to content', fr: 'Aller au contenu' },
  { pt: 'Navegação principal', en: 'Main navigation', fr: 'Navigation principale' },
  { pt: 'Início', en: 'Home', fr: 'Accueil' },
  { pt: 'Serviços', en: 'Services', fr: 'Services' },
  { pt: 'Profissionais', en: 'Professionals', fr: 'Professionnels' },
  { pt: 'sua casa', en: 'your home', fr: 'votre maison' },
  { pt: 'Como funciona', en: 'How it works', fr: 'Comment ça marche' },
  { pt: 'Meu painel', en: 'My dashboard', fr: 'Mon tableau de bord' },
  { pt: 'Entrar', en: 'Sign in', fr: 'Se connecter' },
  { pt: 'Criar conta', en: 'Create account', fr: 'Créer un compte' },
  { pt: 'Fechar menu', en: 'Close menu', fr: 'Fermer le menu' },
  { pt: 'Abrir menu', en: 'Open menu', fr: 'Ouvrir le menu' },
  { pt: 'Mais opções', en: 'More options', fr: "Plus d’options" },
  { pt: 'Segurança', en: 'Safety', fr: 'Sécurité' },
  { pt: 'Ajuda', en: 'Help', fr: 'Aide' },
  { pt: 'Cuidado profissional para sua casa, do seu jeito.', en: 'Professional home care, your way.', fr: 'Des services professionnels à domicile, à votre façon.' },
  { pt: 'Atendimento', en: 'Support', fr: 'Assistance' },
  { pt: 'Central de ajuda', en: 'Help center', fr: "Centre d’aide" },
  { pt: 'Termos de uso', en: 'Terms of use', fr: "Conditions d’utilisation" },
  { pt: 'Privacidade', en: 'Privacy', fr: 'Confidentialité' },
  { pt: 'Para profissionais', en: 'For professionals', fr: 'Pour les professionnels' },
  { pt: 'Quero prestar serviços', en: 'Become a professional', fr: 'Devenir professionnel' },
  { pt: 'Acessar painel', en: 'Open dashboard', fr: 'Accéder au tableau de bord' },
  { pt: 'Feito para servir bem.', en: 'Made to serve you well.', fr: 'Conçu pour mieux vous servir.' },
  { pt: 'Atalhos do aplicativo', en: 'App shortcuts', fr: "Raccourcis de l’application" },
  { pt: 'Conta', en: 'Account', fr: 'Compte' },
  { pt: 'Tudo em um só lugar', en: 'Everything in one place', fr: 'Tout au même endroit' },
  { pt: 'Do que sua casa precisa?', en: 'What does your home need?', fr: 'De quoi votre maison a-t-elle besoin ?' },
  { pt: 'Ver todos', en: 'View all', fr: 'Tout voir' },
  { pt: 'Buscando os melhores serviços para você.', en: 'Finding the best services for you.', fr: 'Recherche des meilleurs services pour vous.' },
  { pt: 'Não conseguimos carregar os serviços', en: 'We could not load the services', fr: "Nous n’avons pas pu charger les services" },
  { pt: 'Escolhas populares', en: 'Popular choices', fr: 'Choix populaires' },
  { pt: 'Serviços mais procurados', en: 'Most requested services', fr: 'Services les plus demandés' },
  { pt: 'Selecionados para você', en: 'Selected for you', fr: 'Sélectionnés pour vous' },
  { pt: 'Profissionais bem avaliados', en: 'Top-rated professionals', fr: 'Professionnels les mieux notés' },
  { pt: 'Resolva em três passos', en: 'Get it done in three steps', fr: 'Réglez tout en trois étapes' },
  { pt: 'Conte o que precisa', en: 'Tell us what you need', fr: 'Décrivez votre besoin' },
  { pt: 'Responda perguntas rápidas para calcular uma estimativa justa.', en: 'Answer a few quick questions to get a fair estimate.', fr: 'Répondez à quelques questions pour obtenir une estimation juste.' },
  { pt: 'Escolha com confiança', en: 'Choose with confidence', fr: 'Choisissez en toute confiance' },
  { pt: 'Compare avaliações, experiências, preço e disponibilidade.', en: 'Compare reviews, experience, price and availability.', fr: 'Comparez les avis, l’expérience, le prix et les disponibilités.' },
  { pt: 'Acompanhe em um só lugar', en: 'Manage everything in one place', fr: 'Gérez tout au même endroit' },
  { pt: 'Converse, acompanhe e avalie pelo seu painel com segurança.', en: 'Message, track and review securely from your dashboard.', fr: 'Échangez, suivez et laissez un avis en toute sécurité depuis votre tableau de bord.' },
  { pt: 'Ofereça seus serviços com autonomia.', en: 'Offer your services on your terms.', fr: 'Proposez vos services en toute autonomie.' },
  { pt: 'Organize sua agenda e receba oportunidades pela plataforma.', en: 'Organize your schedule and receive opportunities through the platform.', fr: 'Organisez votre agenda et recevez des opportunités via la plateforme.' },
  { pt: 'Defina sua disponibilidade', en: 'Set your availability', fr: 'Définissez vos disponibilités' },
  { pt: 'Escolha as oportunidades', en: 'Choose your opportunities', fr: 'Choisissez vos missions' },
  { pt: 'Quero ser profissional', en: 'Become a professional', fr: 'Devenir professionnel' },
  { pt: 'Profissionais disponíveis', en: 'Available professionals', fr: 'Professionnels disponibles' },
  { pt: 'Cuidado profissional para sua casa', en: 'Professional care for your home', fr: 'Des services professionnels pour votre maison' },
  { pt: 'A melhor solução para o seu lar.', en: 'The best solution for your home.', fr: 'La meilleure solution pour votre maison.' },
  { pt: 'Compare profissionais, escolha o melhor horário e acompanhe tudo pela plataforma.', en: 'Compare professionals, choose the best time and manage everything on the platform.', fr: 'Comparez les professionnels, choisissez le meilleur horaire et gérez tout sur la plateforme.' },
  { pt: 'Qual serviço você precisa?', en: 'What service do you need?', fr: 'De quel service avez-vous besoin ?' },
  { pt: 'Buscar', en: 'Search', fr: 'Rechercher' },
  { pt: 'Oferta de boas-vindas', en: 'Welcome offer', fr: 'Offre de bienvenue' },
  { pt: '10% na primeira reserva', en: '10% off your first booking', fr: '10 % sur votre première réservation' },
  { pt: 'Limpeza', en: 'Cleaning', fr: 'Ménage' },
  { pt: 'Lavagem', en: 'Laundry', fr: 'Linge' },
  { pt: 'Reparos', en: 'Repairs', fr: 'Réparations' },
  { pt: 'Pintura', en: 'Painting', fr: 'Peinture' },
  { pt: 'Prévia de agendamento', en: 'Booking preview', fr: 'Aperçu de réservation' },
  { pt: 'Perfil aprovado', en: 'Approved profile', fr: 'Profil approuvé' },
  { pt: 'Serviço', en: 'Service', fr: 'Service' },
  { pt: 'Limpeza residencial', en: 'Home cleaning', fr: 'Ménage à domicile' },
  { pt: 'Horário', en: 'Time', fr: 'Heure' },
  { pt: 'Qui, 14h', en: 'Thu, 2 PM', fr: 'Jeu., 14 h' },
  { pt: 'Agendar agora', en: 'Book now', fr: 'Réserver maintenant' },
  { pt: 'Em destaque', en: 'Featured', fr: 'À la une' },
  { pt: 'Serviços em destaque', en: 'Featured services', fr: 'Services à la une' },
  { pt: 'Perfis aprovados', en: 'Approved profiles', fr: 'Profils approuvés' },
  { pt: 'Serviços para sua casa, sem complicação.', en: 'Home services, made simple.', fr: 'Les services à domicile, en toute simplicité.' },
  { pt: 'Escolha, compare e agende em poucos minutos.', en: 'Choose, compare and book in minutes.', fr: 'Choisissez, comparez et réservez en quelques minutes.' },
  { pt: 'Explorar serviços', en: 'Explore services', fr: 'Découvrir les services' },
  { pt: 'Preço transparente', en: 'Transparent pricing', fr: 'Prix transparents' },
  { pt: 'Suporte na plataforma', en: 'In-platform support', fr: 'Assistance sur la plateforme' },
  { pt: 'Catálogo completo', en: 'Full catalog', fr: 'Catalogue complet' },
  { pt: 'Encontre o serviço certo', en: 'Find the right service', fr: 'Trouvez le service adapté' },
  { pt: 'Profissionais para cuidar da casa, da rotina e de quem você ama.', en: 'Professionals to care for your home, your routine and the people you love.', fr: 'Des professionnels pour votre maison, votre quotidien et vos proches.' },
  { pt: 'Buscar serviço', en: 'Search services', fr: 'Rechercher un service' },
  { pt: 'Busque por limpeza, montagem, pet...', en: 'Search cleaning, assembly, pet care...', fr: 'Recherchez ménage, montage, garde d’animaux...' },
  { pt: 'Filtrar por categoria', en: 'Filter by category', fr: 'Filtrer par catégorie' },
  { pt: 'Todos', en: 'All', fr: 'Tous' },
  { pt: 'Preço inicial, sujeito aos detalhes da solicitação', en: 'Starting price, subject to request details', fr: 'Prix de départ, selon les détails de la demande' },
  { pt: 'O catálogo não carregou', en: 'The catalog could not be loaded', fr: "Le catalogue n’a pas pu être chargé" },
  { pt: 'Nenhum serviço encontrado', en: 'No services found', fr: 'Aucun service trouvé' },
  { pt: 'Tente outro termo ou remova um dos filtros.', en: 'Try another term or remove a filter.', fr: 'Essayez un autre terme ou retirez un filtre.' },
  { pt: 'Profissionais perto de você', en: 'Professionals near you', fr: 'Des professionnels près de chez vous' },
  { pt: 'Perfis aprovados, avaliações publicadas e disponibilidade clara.', en: 'Approved profiles, published reviews and clear availability.', fr: 'Profils approuvés, avis publiés et disponibilités claires.' },
  { pt: 'Filtros', en: 'Filters', fr: 'Filtres' },
  { pt: 'Limpar', en: 'Clear', fr: 'Effacer' },
  { pt: 'Todos os serviços', en: 'All services', fr: 'Tous les services' },
  { pt: 'Cidade', en: 'City', fr: 'Ville' },
  { pt: 'Ex.: São Paulo', en: 'E.g. Brussels', fr: 'Ex. : Bruxelles' },
  { pt: 'Avaliação mínima', en: 'Minimum rating', fr: 'Note minimale' },
  { pt: 'Todas', en: 'Any', fr: 'Toutes' },
  { pt: 'Ordenar resultados', en: 'Sort results', fr: 'Trier les résultats' },
  { pt: 'Recomendados', en: 'Recommended', fr: 'Recommandés' },
  { pt: 'Melhor avaliação', en: 'Highest rated', fr: 'Mieux notés' },
  { pt: 'Menor preço', en: 'Lowest price', fr: 'Prix le plus bas' },
  { pt: 'Não conseguimos buscar profissionais', en: 'We could not find professionals', fr: "Nous n’avons pas pu trouver de professionnels" },
  { pt: 'Nenhum profissional com esses filtros', en: 'No professionals match these filters', fr: 'Aucun professionnel ne correspond à ces filtres' },
  { pt: 'Amplie a cidade, serviço ou avaliação para ver mais opções.', en: 'Broaden the city, service or rating to see more options.', fr: 'Élargissez la ville, le service ou la note pour voir plus d’options.' },
  { pt: 'Abrindo o perfil profissional.', en: 'Opening the professional profile.', fr: 'Ouverture du profil professionnel.' },
  { pt: 'Perfil indisponível', en: 'Profile unavailable', fr: 'Profil indisponible' },
  { pt: 'Remover dos favoritos', en: 'Remove from favorites', fr: 'Retirer des favoris' },
  { pt: 'Adicionar aos favoritos', en: 'Add to favorites', fr: 'Ajouter aux favoris' },
  { pt: 'Sobre', en: 'About', fr: 'À propos' },
  { pt: 'serviços concluídos', en: 'completed services', fr: 'services terminés' },
  { pt: 'anos de experiência', en: 'years of experience', fr: 'ans d’expérience' },
  { pt: 'avaliações de reservas', en: 'booking reviews', fr: 'avis de réservation' },
  { pt: 'atual', en: 'present', fr: "aujourd’hui" },
  { pt: 'Nota de', en: 'Rating', fr: 'Note de' },
  { pt: 'comentários', en: 'comments', fr: 'commentaires' },
  { pt: 'comentário', en: 'comment', fr: 'commentaire' },
  { pt: 'tempo de resposta', en: 'response time', fr: 'temps de réponse' },
  { pt: 'avaliação média', en: 'average rating', fr: 'note moyenne' },
  { pt: 'Serviços oferecidos', en: 'Services offered', fr: 'Services proposés' },
  { pt: 'Avaliações', en: 'Reviews', fr: 'Avis' },
  { pt: 'Perfil aprovado na plataforma', en: 'Platform-approved profile', fr: 'Profil approuvé par la plateforme' },
  { pt: 'Avaliações de reservas', en: 'booking reviews', fr: 'avis de réservations' },
  { pt: 'Trajetória', en: 'Career path', fr: 'Parcours' },
  { pt: 'Experiência profissional', en: 'Professional experience', fr: 'Expérience professionnelle' },
  { pt: 'Formação', en: 'Training', fr: 'Formation' },
  { pt: 'Cursos e certificados', en: 'Courses and certificates', fr: 'Cours et certificats' },
  { pt: 'Avaliações verificadas', en: 'Verified reviews', fr: 'Avis vérifiés' },
  { pt: 'Somente clientes que fecharam negócio pela plataforma podem avaliar com estrelas.', en: 'Only customers who completed a booking through the platform can leave a star rating.', fr: 'Seuls les clients ayant finalisé une réservation via la plateforme peuvent attribuer une note.' },
  { pt: 'Reserva verificada', en: 'Verified booking', fr: 'Réservation vérifiée' },
  { pt: 'Resposta do profissional', en: 'Professional reply', fr: 'Réponse du professionnel' },
  { pt: 'Comunidade', en: 'Community', fr: 'Communauté' },
  { pt: 'Comentários públicos', en: 'Public comments', fr: 'Commentaires publics' },
  { pt: 'Espaço para comentários de membros da plataforma. Não altera a nota profissional.', en: 'A space for comments from platform members. It does not affect the professional rating.', fr: 'Un espace pour les commentaires des membres de la plateforme. Ils n’affectent pas la note du professionnel.' },
  { pt: 'Comentário da comunidade', en: 'Community comment', fr: 'Commentaire de la communauté' },
  { pt: 'Quer deixar um comentário?', en: 'Want to leave a comment?', fr: 'Vous souhaitez laisser un commentaire ?' },
  { pt: 'Entre na sua conta', en: 'Sign in to your account', fr: 'Connectez-vous à votre compte' },
  { pt: 'Deixe um comentário', en: 'Leave a comment', fr: 'Laissez un commentaire' },
  { pt: 'Compartilhe uma observação respeitosa e útil.', en: 'Share a respectful and helpful observation.', fr: 'Partagez une observation respectueuse et utile.' },
  { pt: 'Publicando…', en: 'Publishing…', fr: 'Publication…' },
  { pt: 'Publicar comentário', en: 'Publish comment', fr: 'Publier le commentaire' },
  { pt: 'Escreva pelo menos 3 caracteres.', en: 'Write at least 3 characters.', fr: 'Écrivez au moins 3 caractères.' },
  { pt: 'Ainda não há comentários públicos.', en: 'There are no public comments yet.', fr: 'Il n’y a pas encore de commentaires publics.' },
  { pt: 'Vitrine pública', en: 'Public showcase', fr: 'Vitrine publique' },
  { pt: 'Dados pessoais', en: 'Personal details', fr: 'Informations personnelles' },
  { pt: 'Sua identidade na plataforma', en: 'Your platform identity', fr: 'Votre identité sur la plateforme' },
  { pt: 'Foto de perfil', en: 'Profile photo', fr: 'Photo de profil' },
  { pt: 'Conversa protegida', en: 'Protected conversation', fr: 'Conversation protégée' },
  { pt: 'Suas conversas', en: 'Your conversations', fr: 'Vos conversations' },
  { pt: 'Reserva confirmada', en: 'Booking confirmed', fr: 'Réservation confirmée' },
  { pt: 'A caminho', en: 'On the way', fr: 'En route' },
  { pt: 'Em andamento', en: 'In progress', fr: 'En cours' },
  { pt: 'Serviço concluído', en: 'Service completed', fr: 'Service terminé' },
  { pt: 'As próximas avaliações aparecerão aqui.', en: 'New reviews will appear here.', fr: 'Les nouveaux avis apparaîtront ici.' },
  { pt: 'Próximo horário', en: 'Next availability', fr: 'Prochaine disponibilité' },
  { pt: 'A partir de', en: 'From', fr: 'À partir de' },
  { pt: 'Preço calculado na reserva', en: 'Price calculated at booking', fr: 'Prix calculé lors de la réservation' },
  { pt: 'Escolher este profissional', en: 'Choose this professional', fr: 'Choisir ce professionnel' },
  { pt: 'Revise todos os detalhes antes de confirmar.', en: 'Review all details before confirming.', fr: 'Vérifiez tous les détails avant de confirmer.' },
  { pt: 'Valor', en: 'Price', fr: 'Prix' },
  { pt: 'na reserva', en: 'at booking', fr: 'à la réservation' },
  { pt: 'Agendar', en: 'Book', fr: 'Réserver' },
  { pt: 'Serviço indisponível', en: 'Service unavailable', fr: 'Service indisponible' },
  { pt: 'Agendamento simples e seguro', en: 'Simple, secure booking', fr: 'Réservation simple et sécurisée' },
  { pt: 'Informações e avaliações para ajudar você a escolher, sem alegação de certificação de identidade.', en: 'Information and reviews to help you choose, without claiming identity certification.', fr: 'Des informations et des avis pour vous aider à choisir, sans prétendre certifier l’identité.' },
  { pt: 'Veja a composição do valor antes de confirmar.', en: 'See the price breakdown before confirming.', fr: 'Consultez le détail du prix avant de confirmer.' },
  { pt: 'Suporte durante o serviço', en: 'Support during the service', fr: 'Assistance pendant le service' },
  { pt: 'Converse e acompanhe tudo pelo seu painel.', en: 'Message and follow everything from your dashboard.', fr: 'Échangez et suivez tout depuis votre tableau de bord.' },
  { pt: 'Disponíveis para você', en: 'Available for you', fr: 'Disponibles pour vous' },
  { pt: 'Profissionais para', en: 'Professionals for', fr: 'Professionnels pour' },
  { pt: 'Quer acompanhar uma reserva?', en: 'Want to track a booking?', fr: 'Vous souhaitez suivre une réservation ?' },
  { pt: 'Entre na sua conta para consultar detalhes, cancelamentos, notificações e conversas disponíveis.', en: 'Sign in to view details, cancellations, notifications and conversations.', fr: 'Connectez-vous pour consulter les détails, annulations, notifications et conversations.' },
  { pt: 'Acessar minha conta', en: 'Open my account', fr: 'Accéder à mon compte' },
  { pt: 'Essa página não está por aqui.', en: 'This page is not here.', fr: "Cette page n’existe pas." },
  { pt: 'Talvez o endereço tenha mudado ou o link esteja incompleto.', en: 'The address may have changed or the link may be incomplete.', fr: "L’adresse a peut-être changé ou le lien est incomplet." },
  { pt: 'Voltar ao início', en: 'Back to home', fr: "Retour à l’accueil" },
  { pt: 'Visão geral', en: 'Overview', fr: 'Vue d’ensemble' },
  { pt: 'Agendamentos', en: 'Bookings', fr: 'Réservations' },
  { pt: 'Agenda', en: 'Schedule', fr: 'Agenda' },
  { pt: 'Mensagens', en: 'Messages', fr: 'Messages' },
  { pt: 'Favoritos', en: 'Favorites', fr: 'Favoris' },
  { pt: 'Perfil e preferências', en: 'Profile and preferences', fr: 'Profil et préférences' },
  { pt: 'Solicitações', en: 'Requests', fr: 'Demandes' },
  { pt: 'Pedidos', en: 'Requests', fr: 'Demandes' },
  { pt: 'Minha agenda', en: 'My schedule', fr: 'Mon agenda' },
  { pt: 'Resumo de serviços', en: 'Service summary', fr: 'Résumé des services' },
  { pt: 'Atividade', en: 'Activity', fr: 'Activité' },
  { pt: 'Serviços e perfil', en: 'Services and profile', fr: 'Services et profil' },
  { pt: 'Reservas', en: 'Bookings', fr: 'Réservations' },
  { pt: 'Clientes', en: 'Customers', fr: 'Clients' },
  { pt: 'Prestadores', en: 'Providers', fr: 'Prestataires' },
  { pt: 'Catálogo', en: 'Catalog', fr: 'Catalogue' },
  { pt: 'Suporte', en: 'Support', fr: 'Assistance' },
  { pt: 'Configurações', en: 'Settings', fr: 'Paramètres' },
  { pt: 'Ajustes', en: 'Settings', fr: 'Paramètres' },
  { pt: 'Área do profissional', en: 'Professional area', fr: 'Espace professionnel' },
  { pt: 'Administração', en: 'Administration', fr: 'Administration' },
  { pt: 'Área do cliente', en: 'Customer area', fr: 'Espace client' },
  { pt: 'Navegação do painel', en: 'Dashboard navigation', fr: 'Navigation du tableau de bord' },
  { pt: 'Precisa de ajuda?', en: 'Need help?', fr: "Besoin d’aide ?" },
  { pt: 'Fechar notificações', en: 'Close notifications', fr: 'Fermer les notifications' },
  { pt: 'Abrir notificações', en: 'Open notifications', fr: 'Ouvrir les notifications' },
  { pt: 'Notificações', en: 'Notifications', fr: 'Notifications' },
  { pt: 'Marcar todas como lidas', en: 'Mark all as read', fr: 'Tout marquer comme lu' },
  { pt: 'Carregando…', en: 'Loading…', fr: 'Chargement…' },
  { pt: 'Nenhuma notificação.', en: 'No notifications.', fr: 'Aucune notification.' },
  { pt: 'Sair', en: 'Sign out', fr: 'Se déconnecter' },
  { pt: 'Atalhos do painel', en: 'Dashboard shortcuts', fr: 'Raccourcis du tableau de bord' },
  { pt: 'Mais', en: 'More', fr: 'Plus' },
  { pt: 'ChezVoust Pro, página inicial', en: 'ChezVoust Pro, home page', fr: "ChezVoust Pro, page d’accueil" },
  { pt: 'Profissional de limpeza sorrindo com luvas e frasco de limpeza', en: 'Smiling cleaning professional wearing gloves and holding a cleaning bottle', fr: 'Professionnelle du ménage souriante avec des gants et un flacon de nettoyage' },
  { pt: 'Eletricista residencial sorrindo com alicate e multímetro', en: 'Smiling residential electrician with pliers and a multimeter', fr: 'Électricien résidentiel souriant avec une pince et un multimètre' },
  { pt: 'Garçonete profissional sorrindo com uma bandeja', en: 'Smiling professional server holding a tray', fr: 'Serveuse professionnelle souriante avec un plateau' },
  { pt: 'Lavanderia', en: 'Laundry', fr: 'Linge' },
  { pt: 'Montagem', en: 'Assembly', fr: 'Montage' },
  { pt: 'Jardinagem', en: 'Gardening', fr: 'Jardinage' },
  { pt: 'Organização', en: 'Organization', fr: 'Organisation' },
  { pt: 'Eletricista residencial', en: 'Residential electrician', fr: 'Électricien résidentiel' },
  { pt: 'Instalações e pequenos reparos elétricos.', en: 'Electrical installations and minor repairs.', fr: 'Installations électriques et petites réparations.' },
  { pt: 'Lavanderia de roupas', en: 'Clothes laundry', fr: 'Entretien du linge' },
  { pt: 'Lavagem de roupas', en: 'Clothes laundry', fr: 'Entretien du linge' },
  { pt: 'Lavagem e separação cuidadosa de roupas.', en: 'Careful washing and sorting of clothes.', fr: 'Lavage et tri soigneux du linge.' },
  { pt: 'Limpeza completa para sua casa.', en: 'Complete cleaning for your home.', fr: 'Nettoyage complet de votre maison.' },
  { pt: 'Faxina pesada', en: 'Deep cleaning', fr: 'Nettoyage en profondeur' },
  { pt: 'Limpeza profunda para ambientes que precisam de cuidado extra.', en: 'Deep cleaning for spaces that need extra care.', fr: 'Nettoyage en profondeur pour les espaces qui nécessitent un soin particulier.' },
  { pt: 'Passadoria', en: 'Ironing', fr: 'Repassage' },
  { pt: 'Roupas passadas e organizadas.', en: 'Clothes ironed and organized.', fr: 'Vêtements repassés et rangés.' },
  { pt: 'Encanador residencial', en: 'Residential plumber', fr: 'Plombier résidentiel' },
  { pt: 'Soluções para vazamentos e instalações hidráulicas.', en: 'Solutions for leaks and plumbing installations.', fr: 'Solutions pour les fuites et installations de plomberie.' },
  { pt: 'Pintura interna', en: 'Interior painting', fr: 'Peinture intérieure' },
  { pt: 'Renove paredes e tetos internos.', en: 'Refresh interior walls and ceilings.', fr: 'Rénovez les murs et plafonds intérieurs.' },
  { pt: 'Manutenção de jardim', en: 'Garden maintenance', fr: 'Entretien du jardin' },
  { pt: 'Poda, limpeza e cuidado com áreas verdes.', en: 'Pruning, cleaning and care for green spaces.', fr: 'Taille, nettoyage et entretien des espaces verts.' },
  { pt: 'Organização de ambientes', en: 'Home organization', fr: 'Organisation des espaces' },
  { pt: 'Mais praticidade para armários e cômodos.', en: 'More practical, organized closets and rooms.', fr: 'Des placards et des pièces plus pratiques et mieux organisés.' },
  { pt: 'hora', en: 'hour', fr: 'heure' },
  { pt: 'serviço', en: 'service', fr: 'service' },
  { pt: 'diária', en: 'day', fr: 'jour' },
  { pt: 'Montagem de móveis', en: 'Furniture assembly', fr: 'Montage de meubles' },
  { pt: 'Montagem segura de móveis residenciais.', en: 'Safe assembly of home furniture.', fr: 'Montage sécurisé de meubles à domicile.' },
  { pt: 'Especialista em limpeza e pequenos reparos', en: 'Cleaning and minor repairs specialist', fr: 'Spécialiste du ménage et des petites réparations' },
  { pt: 'Limpeza residencial com atenção aos detalhes', en: 'Detail-oriented home cleaning', fr: 'Ménage à domicile avec soin du détail' },
  { pt: 'Suporte pela plataforma', en: 'In-platform support', fr: 'Assistance sur la plateforme' },
  { pt: 'Diferenciais', en: 'Highlights', fr: 'Points forts' },
  { pt: 'Próximo horário:', en: 'Next availability:', fr: 'Prochaine disponibilité :' },
  { pt: 'Consulte a agenda', en: 'Check the schedule', fr: "Consulter l’agenda" },
  { pt: 'Ver perfil', en: 'View profile', fr: 'Voir le profil' },
  { pt: 'Preço na proposta', en: 'Price in proposal', fr: 'Prix dans la proposition' },
  { pt: 'Mais pedido', en: 'Most requested', fr: 'Le plus demandé' },
  { pt: 'Só um instante enquanto organizamos tudo.', en: 'Just a moment while we get everything ready.', fr: 'Un instant, nous préparons tout.' },
  { pt: 'Nada por aqui ainda', en: 'Nothing here yet', fr: 'Rien ici pour le moment' },
  { pt: 'Tentar novamente', en: 'Try again', fr: 'Réessayer' },
  { pt: 'Bem-vindo de volta', en: 'Welcome back', fr: 'Bon retour' },
  { pt: 'Sua casa e seus serviços em um só lugar.', en: 'Your home and services in one place.', fr: 'Votre maison et vos services au même endroit.' },
  { pt: 'Acompanhe reservas, converse com profissionais e organize seus serviços com tranquilidade.', en: 'Track bookings, message professionals and organize your services with confidence.', fr: 'Suivez vos réservations, échangez avec les professionnels et organisez vos services sereinement.' },
  { pt: 'Use seu e-mail e senha para continuar.', en: 'Use your email and password to continue.', fr: 'Utilisez votre e-mail et votre mot de passe pour continuer.' },
  { pt: 'Conta criada.', en: 'Account created.', fr: 'Compte créé.' },
  { pt: 'Agora entre para acessar seu painel.', en: 'Sign in now to access your dashboard.', fr: 'Connectez-vous maintenant pour accéder à votre tableau de bord.' },
  { pt: 'Não foi possível entrar.', en: 'Unable to sign in.', fr: 'Connexion impossible.' },
  { pt: 'E-mail', en: 'Email', fr: 'E-mail' },
  { pt: 'Informe um e-mail válido.', en: 'Enter a valid email address.', fr: 'Saisissez une adresse e-mail valide.' },
  { pt: 'Senha', en: 'Password', fr: 'Mot de passe' },
  { pt: 'Esqueci minha senha', en: 'Forgot my password', fr: 'Mot de passe oublié' },
  { pt: 'A senha é obrigatória.', en: 'Password is required.', fr: 'Le mot de passe est obligatoire.' },
  { pt: 'Manter acesso neste dispositivo', en: 'Keep me signed in on this device', fr: 'Rester connecté sur cet appareil' },
  { pt: 'Entrando...', en: 'Signing in...', fr: 'Connexion...' },
  { pt: 'ou acesse a demonstração', en: 'or use a demo account', fr: 'ou utiliser un compte de démonstration' },
  { pt: 'Contas de demonstração', en: 'Demo accounts', fr: 'Comptes de démonstration' },
  { pt: 'Cliente', en: 'Customer', fr: 'Client' },
  { pt: 'Profissional', en: 'Professional', fr: 'Professionnel' },
  { pt: 'Ainda não tem conta?', en: 'Do not have an account yet?', fr: "Vous n’avez pas encore de compte ?" },
  { pt: 'Crie sua conta', en: 'Create your account', fr: 'Créez votre compte' },
  { pt: 'Comece agora', en: 'Get started', fr: 'Commencez maintenant' },
  { pt: 'Transforme seu talento em oportunidades.', en: 'Turn your talent into opportunities.', fr: 'Transformez votre talent en opportunités.' },
  { pt: 'Mais tempo para o que importa.', en: 'More time for what matters.', fr: 'Plus de temps pour ce qui compte.' },
  { pt: 'Monte seu perfil, escolha sua região e organize sua agenda.', en: 'Build your profile, choose your area and organize your schedule.', fr: 'Créez votre profil, choisissez votre zone et organisez votre agenda.' },
  { pt: 'Encontre pessoas de confiança para cuidar da sua rotina.', en: 'Find trusted people to help with your routine.', fr: 'Trouvez des personnes de confiance pour votre quotidien.' },
  { pt: 'Voltar', en: 'Back', fr: 'Retour' },
  { pt: 'Criar conta profissional', en: 'Create a professional account', fr: 'Créer un compte professionnel' },
  { pt: 'Leva menos de dois minutos.', en: 'It takes less than two minutes.', fr: 'Cela prend moins de deux minutes.' },
  { pt: 'Nome completo', en: 'Full name', fr: 'Nom complet' },
  { pt: 'Informe seu nome completo.', en: 'Enter your full name.', fr: 'Saisissez votre nom complet.' },
  { pt: 'Celular', en: 'Mobile phone', fr: 'Téléphone portable' },
  { pt: 'Informe um celular válido.', en: 'Enter a valid mobile number.', fr: 'Saisissez un numéro de portable valide.' },
  { pt: 'Use 8 caracteres, com maiúscula, minúscula, número e símbolo.', en: 'Use 8 characters with uppercase, lowercase, a number and a symbol.', fr: 'Utilisez 8 caractères avec majuscule, minuscule, chiffre et symbole.' },
  { pt: 'Li e aceito os', en: 'I have read and accept the', fr: "J’ai lu et j’accepte les" },
  { pt: 'Termos', en: 'Terms', fr: 'Conditions' },
  { pt: 'Aviso de privacidade', en: 'Privacy notice', fr: 'Avis de confidentialité' },
  { pt: 'Criando conta...', en: 'Creating account...', fr: 'Création du compte...' },
  { pt: 'Criar minha conta', en: 'Create my account', fr: 'Créer mon compte' },
  { pt: 'Já tem conta?', en: 'Already have an account?', fr: 'Vous avez déjà un compte ?' },
  { pt: 'Quero contratar serviços', en: 'I want to hire services', fr: 'Je cherche des services' },
  { pt: 'Acesso protegido', en: 'Protected access', fr: 'Accès protégé' },
  { pt: 'Recupere sua conta com tranquilidade.', en: 'Recover your account securely.', fr: 'Récupérez votre compte en toute sécurité.' },
  { pt: 'Enviaremos as instruções para o e-mail cadastrado, sem expor se a conta existe.', en: 'We will send instructions to the registered email without revealing whether the account exists.', fr: "Nous enverrons les instructions à l’adresse enregistrée sans révéler si le compte existe." },
  { pt: 'Voltar para entrar', en: 'Back to sign in', fr: 'Retour à la connexion' },
  { pt: 'Recuperar senha', en: 'Recover password', fr: 'Récupérer le mot de passe' },
  { pt: 'Digite seu e-mail e enviaremos as instruções.', en: 'Enter your email and we will send the instructions.', fr: 'Saisissez votre e-mail et nous vous enverrons les instructions.' },
  { pt: 'Enviando…', en: 'Sending…', fr: 'Envoi…' },
  { pt: 'Enviar instruções', en: 'Send instructions', fr: 'Envoyer les instructions' },
  { pt: 'Confira seu e-mail', en: 'Check your email', fr: 'Consultez votre e-mail' },
  { pt: 'Crie uma nova senha.', en: 'Create a new password.', fr: 'Créez un nouveau mot de passe.' },
  { pt: 'Senha atualizada', en: 'Password updated', fr: 'Mot de passe mis à jour' },
  { pt: 'Redefinir senha', en: 'Reset password', fr: 'Réinitialiser le mot de passe' },
  { pt: 'Nova senha', en: 'New password', fr: 'Nouveau mot de passe' },
  { pt: 'Confirmar senha', en: 'Confirm password', fr: 'Confirmer le mot de passe' },
  { pt: 'Atualizando…', en: 'Updating…', fr: 'Mise à jour…' },
  { pt: 'Atualizar senha', en: 'Update password', fr: 'Mettre à jour le mot de passe' },
  { pt: 'Conte um pouco mais', en: 'Tell us a little more', fr: 'Dites-nous-en un peu plus' },
  { pt: 'Como será o serviço?', en: 'What will the service involve?', fr: 'Comment se déroulera le service ?' },
  { pt: 'Usamos esses detalhes para calcular o valor no servidor e preparar o profissional.', en: 'We use these details to calculate the server-side price and prepare the professional.', fr: 'Nous utilisons ces détails pour calculer le prix côté serveur et préparer le professionnel.' },
  { pt: 'Trocar', en: 'Change', fr: 'Changer' },
  { pt: 'Tamanho aproximado da área', en: 'Approximate area size', fr: 'Surface approximative' },
  { pt: 'Duração estimada', en: 'Estimated duration', fr: 'Durée estimée' },
  { pt: 'Quantidade de profissionais/unidades', en: 'Number of professionals/units', fr: 'Nombre de professionnels/unités' },
  { pt: 'Quantidade', en: 'Quantity', fr: 'Quantité' },
  { pt: 'Preço por serviço', en: 'Price per service', fr: 'Prix par service' },
  { pt: 'Adicionais', en: 'Add-ons', fr: 'Options' },
  { pt: 'Opcional', en: 'Optional', fr: 'Facultatif' },
  { pt: 'Observações para o profissional', en: 'Notes for the professional', fr: 'Notes pour le professionnel' },
  { pt: 'Ex.: tenho dois gatos; trazer escada...', en: 'E.g. I have two cats; bring a ladder...', fr: "Ex. : j’ai deux chats ; apporter une échelle..." },
  { pt: 'Local do atendimento', en: 'Service location', fr: "Lieu de l’intervention" },
  { pt: 'Onde o serviço será realizado?', en: 'Where will the service take place?', fr: 'Où le service aura-t-il lieu ?' },
  { pt: 'O endereço completo só será compartilhado depois da confirmação.', en: 'The full address is only shared after confirmation.', fr: "L’adresse complète n’est communiquée qu’après confirmation." },
  { pt: 'Endereços salvos', en: 'Saved addresses', fr: 'Adresses enregistrées' },
  { pt: 'Endereço', en: 'Address', fr: 'Adresse' },
  { pt: 'Principal', en: 'Primary', fr: 'Principale' },
  { pt: 'ou informe outro endereço', en: 'or enter another address', fr: 'ou saisissez une autre adresse' },
  { pt: 'Rua', en: 'Street', fr: 'Rue' },
  { pt: 'Número', en: 'Number', fr: 'Numéro' },
  { pt: 'Complemento', en: 'Address details', fr: "Complément d’adresse" },
  { pt: 'Bairro', en: 'Neighborhood', fr: 'Quartier' },
  { pt: 'Estado', en: 'State', fr: 'Région' },
  { pt: 'Selecione', en: 'Select', fr: 'Sélectionner' },
  { pt: 'Seus dados protegidos', en: 'Your data is protected', fr: 'Vos données sont protégées' },
  { pt: 'Escolha o melhor momento', en: 'Choose the best time', fr: 'Choisissez le meilleur moment' },
  { pt: 'Qual dia e horário?', en: 'Which day and time?', fr: 'Quel jour et quelle heure ?' },
  { pt: 'Data', en: 'Date', fr: 'Date' },
  { pt: 'Consultando as agendas…', en: 'Checking schedules…', fr: 'Consultation des agendas…' },
  { pt: 'Nenhum profissional possui horário livre nesta data.', en: 'No professional has an available time on this date.', fr: "Aucun professionnel n’est disponible à cette date." },
  { pt: 'Confirmação rápida', en: 'Quick confirmation', fr: 'Confirmation rapide' },
  { pt: 'Compare e escolha', en: 'Compare and choose', fr: 'Comparez et choisissez' },
  { pt: 'Quem vai cuidar da sua casa?', en: 'Who will take care of your home?', fr: 'Qui prendra soin de votre maison ?' },
  { pt: 'Receber propostas', en: 'Receive proposals', fr: 'Recevoir des propositions' },
  { pt: 'Sem compromisso', en: 'No commitment', fr: 'Sans engagement' },
  { pt: 'Compare ofertas', en: 'Compare offers', fr: 'Comparer les offres' },
  { pt: 'Após escolher', en: 'After choosing', fr: 'Après votre choix' },
  { pt: 'reserva confirmada', en: 'booking confirmed', fr: 'réservation confirmée' },
  { pt: 'Calcular no resumo', en: 'Calculate in summary', fr: 'Calculer dans le récapitulatif' },
  { pt: 'valor de referência', en: 'reference price', fr: 'prix de référence' },
  { pt: 'Última etapa', en: 'Final step', fr: 'Dernière étape' },
  { pt: 'Revise e confirme', en: 'Review and confirm', fr: 'Vérifiez et confirmez' },
  { pt: 'Detalhes da reserva', en: 'Booking details', fr: 'Détails de la réservation' },
  { pt: 'Data e horário', en: 'Date and time', fr: 'Date et heure' },
  { pt: 'Reserva confirmada', en: 'Booking confirmed', fr: 'Réservation confirmée' },
  { pt: 'Solicitação aberta', en: 'Open request', fr: 'Demande ouverte' },
  { pt: 'Aplicar', en: 'Apply', fr: 'Appliquer' },
  { pt: 'Taxa de serviço', en: 'Service fee', fr: 'Frais de service' },
  { pt: 'Desconto', en: 'Discount', fr: 'Réduction' },
  { pt: 'Estimativa', en: 'Estimate', fr: 'Estimation' },
  { pt: 'Total', en: 'Total', fr: 'Total' },
  { pt: 'Progresso da reserva', en: 'Booking progress', fr: 'Progression de la réservation' },
  { pt: 'Etapa', en: 'Step', fr: 'Étape' },
  { pt: 'de 5', en: 'of 5', fr: 'sur 5' },
  { pt: 'Aberto a propostas', en: 'Open to proposals', fr: 'Ouvert aux propositions' },
  { pt: 'Aguardando confirmação', en: 'Awaiting confirmation', fr: 'En attente de confirmation' },
  { pt: 'Confirmado', en: 'Confirmed', fr: 'Confirmé' },
  { pt: 'Profissional a caminho', en: 'Professional on the way', fr: 'Professionnel en route' },
  { pt: 'Em andamento', en: 'In progress', fr: 'En cours' },
  { pt: 'Concluído', en: 'Completed', fr: 'Terminé' },
  { pt: 'Cancelado', en: 'Cancelled', fr: 'Annulé' },
  { pt: 'Em análise', en: 'Under review', fr: "En cours d’examen" },
  { pt: 'Sua conta', en: 'Your account', fr: 'Votre compte' },
  { pt: 'Seu painel', en: 'Your dashboard', fr: 'Votre tableau de bord' },
  { pt: 'Olá,', en: 'Hello,', fr: 'Bonjour,' },
  { pt: 'Veja o que está acontecendo com seus serviços.', en: 'See what is happening with your services.', fr: 'Découvrez ce qui se passe avec vos services.' },
  { pt: 'Novo serviço', en: 'New service', fr: 'Nouveau service' },
  { pt: 'Agendados', en: 'Scheduled', fr: 'Planifiés' },
  { pt: 'Concluídos', en: 'Completed', fr: 'Terminés' },
  { pt: 'Em acompanhamento', en: 'Being tracked', fr: 'En cours de suivi' },
  { pt: 'No seu histórico', en: 'In your history', fr: 'Dans votre historique' },
  { pt: 'Total gasto', en: 'Total spent', fr: 'Total dépensé' },
  { pt: 'Reservas pagas', en: 'Paid bookings', fr: 'Réservations payées' },
  { pt: 'Nenhum serviço agendado', en: 'No scheduled services', fr: 'Aucun service planifié' },
  { pt: 'Encontre o profissional certo para cuidar da sua próxima tarefa.', en: 'Find the right professional for your next task.', fr: 'Trouvez le professionnel adapté à votre prochaine tâche.' },
  { pt: 'Encontrar serviço', en: 'Find a service', fr: 'Trouver un service' },
  { pt: 'O que você precisa?', en: 'What do you need?', fr: 'De quoi avez-vous besoin ?' },
  { pt: 'Conversas', en: 'Conversations', fr: 'Conversations' },
  { pt: 'Endereços', en: 'Addresses', fr: 'Adresses' },
  { pt: 'Locais', en: 'Locations', fr: 'Lieux' },
  { pt: 'Acompanhe serviços futuros e seu histórico.', en: 'Track upcoming services and your history.', fr: 'Suivez les services à venir et votre historique.' },
  { pt: 'Quando você fizer uma reserva, ela aparecerá nesta lista.', en: 'When you make a booking, it will appear in this list.', fr: 'Lorsque vous effectuerez une réservation, elle apparaîtra dans cette liste.' },
  { pt: 'Encontre rapidamente quem já conquistou sua confiança.', en: 'Quickly find professionals who have already earned your trust.', fr: 'Retrouvez rapidement les professionnels qui ont déjà gagné votre confiance.' },
  { pt: 'Proteção da conta', en: 'Account protection', fr: 'Protection du compte' },
  { pt: 'Senha e dispositivos', en: 'Password and devices', fr: 'Mot de passe et appareils' },
  { pt: 'Sessão protegida', en: 'Protected session', fr: 'Session protégée' },
  { pt: 'Senha atual', en: 'Current password', fr: 'Mot de passe actuel' },
  { pt: 'Use no mínimo 8 caracteres, com maiúscula, minúscula, número e símbolo.', en: 'Use at least 8 characters with uppercase, lowercase, a number and a symbol.', fr: 'Utilisez au moins 8 caractères avec une majuscule, une minuscule, un chiffre et un symbole.' },
  { pt: 'Dispositivos conectados', en: 'Connected devices', fr: 'Appareils connectés' },
  { pt: 'Este dispositivo', en: 'This device', fr: 'Cet appareil' },
  { pt: 'atividade em', en: 'activity on', fr: 'activité le' },
  { pt: 'Navegador em Windows', en: 'Browser on Windows', fr: 'Navigateur sous Windows' },
  { pt: 'Chrome em Windows', en: 'Chrome on Windows', fr: 'Chrome sous Windows' },
  { pt: 'Desconectar', en: 'Disconnect', fr: 'Déconnecter' },
  { pt: 'Sair de todos os dispositivos', en: 'Sign out of all devices', fr: 'Se déconnecter de tous les appareils' },
  { pt: 'Raio', en: 'Radius', fr: 'Rayon' },
  { pt: 'O acesso usa sessão renovável em cookie protegido. Revise abaixo os dispositivos conectados e mantenha sua senha atualizada.', en: 'Access uses a renewable session in a protected cookie. Review connected devices below and keep your password up to date.', fr: 'L’accès utilise une session renouvelable dans un cookie protégé. Vérifiez les appareils connectés ci-dessous et gardez votre mot de passe à jour.' },
  { pt: 'Alterar senha', en: 'Change password', fr: 'Modifier le mot de passe' },
  { pt: 'Confirmar nova senha', en: 'Confirm new password', fr: 'Confirmer le nouveau mot de passe' },
  { pt: 'Revogue acessos que você não reconhece.', en: 'Revoke access you do not recognize.', fr: 'Révoquez les accès que vous ne reconnaissez pas.' },
  { pt: 'Mantenha seus dados atualizados.', en: 'Keep your information up to date.', fr: 'Maintenez vos informations à jour.' },
  { pt: 'Dados pessoais', en: 'Personal information', fr: 'Informations personnelles' },
  { pt: 'Salvar alterações', en: 'Save changes', fr: 'Enregistrer les modifications' },
  { pt: 'Conta protegida', en: 'Protected account', fr: 'Compte protégé' },
  { pt: 'Locais de atendimento', en: 'Service locations', fr: "Lieux d’intervention" },
  { pt: 'Novo endereço', en: 'New address', fr: 'Nouvelle adresse' },
  { pt: 'Editar endereço', en: 'Edit address', fr: "Modifier l’adresse" },
  { pt: 'Adicionar endereço', en: 'Add address', fr: 'Ajouter une adresse' },
  { pt: 'Identificação', en: 'Label', fr: 'Libellé' },
  { pt: 'Casa ou trabalho', en: 'Home or work', fr: 'Domicile ou travail' },
  { pt: 'Usar como endereço principal', en: 'Use as primary address', fr: 'Utiliser comme adresse principale' },
  { pt: 'Sua seleção', en: 'Your selection', fr: 'Votre sélection' },
  { pt: 'Profissionais favoritos', en: 'Favorite professionals', fr: 'Professionnels favoris' },
  { pt: 'Nenhum favorito ainda', en: 'No favorites yet', fr: 'Aucun favori pour le moment' },
  { pt: 'Próximo compromisso', en: 'Next appointment', fr: 'Prochain rendez-vous' },
  { pt: 'Seu próximo serviço', en: 'Your next service', fr: 'Votre prochain service' },
  { pt: 'Atalhos', en: 'Shortcuts', fr: 'Raccourcis' },
  { pt: 'Histórico', en: 'History', fr: 'Historique' },
  { pt: 'Atividade recente', en: 'Recent activity', fr: 'Activité récente' },
  { pt: 'Sua agenda', en: 'Your schedule', fr: 'Votre agenda' },
  { pt: 'Agendamentos indisponíveis', en: 'Bookings unavailable', fr: 'Réservations indisponibles' },
  { pt: 'Nenhum agendamento aqui', en: 'No bookings here', fr: 'Aucune réservation ici' },
  { pt: 'Motivo do cancelamento', en: 'Cancellation reason', fr: "Motif de l’annulation" },
  { pt: 'Confirmar cancelamento', en: 'Confirm cancellation', fr: "Confirmer l’annulation" },
  { pt: 'Enviar avaliação', en: 'Submit review', fr: "Envoyer l’avis" },
  { pt: 'Detalhes da reserva', en: 'Booking details', fr: 'Détails de la réservation' },
  { pt: 'Ações', en: 'Actions', fr: 'Actions' },
  { pt: 'Acompanhamento', en: 'Tracking', fr: 'Suivi' },
  { pt: 'Andamento da reserva', en: 'Booking progress', fr: 'Progression de la réservation' },
  { pt: 'Reagendar', en: 'Reschedule', fr: 'Reprogrammer' },
  { pt: 'Nova data', en: 'New date', fr: 'Nouvelle date' },
  { pt: 'Novo horário', en: 'New time', fr: 'Nouvelle heure' },
  { pt: 'Confirmar novo horário', en: 'Confirm new time', fr: 'Confirmer le nouvel horaire' },
  { pt: 'Propostas recebidas', en: 'Proposals received', fr: 'Propositions reçues' },
  { pt: 'Carregando propostas…', en: 'Loading proposals…', fr: 'Chargement des propositions…' },
  { pt: 'Escolher proposta', en: 'Choose proposal', fr: 'Choisir la proposition' },
  { pt: 'Confirmar proposta', en: 'Confirm proposal', fr: 'Confirmer la proposition' },
  { pt: 'Conversa protegida', en: 'Protected conversation', fr: 'Conversation protégée' },
  { pt: 'Alinhe os detalhes sem sair da plataforma.', en: 'Coordinate details without leaving the platform.', fr: 'Coordonnez les détails sans quitter la plateforme.' },
  { pt: 'Nenhuma conversa ainda', en: 'No conversations yet', fr: 'Aucune conversation pour le moment' },
  { pt: 'Digite uma mensagem', en: 'Type a message', fr: 'Écrivez un message' },
  { pt: 'Área profissional', en: 'Professional area', fr: 'Espace professionnel' },
  { pt: 'Acompanhe a agenda e as oportunidades disponíveis.', en: 'Track your schedule and available opportunities.', fr: 'Suivez votre agenda et les opportunités disponibles.' },
  { pt: 'Oportunidades disponíveis', en: 'Available opportunities', fr: 'Opportunités disponibles' },
  { pt: 'Próximos serviços', en: 'Upcoming services', fr: 'Services à venir' },
  { pt: 'Confirmados na agenda', en: 'Confirmed in the schedule', fr: 'Confirmés dans l’agenda' },
  { pt: 'Sua avaliação', en: 'Your rating', fr: 'Votre note' },
  { pt: 'O perfil está habilitado para receber oportunidades. Isso não representa certificação de identidade.', en: 'The profile can receive opportunities. This does not represent identity certification.', fr: 'Le profil peut recevoir des opportunités. Cela ne constitue pas une certification d’identité.' },
  { pt: 'Nenhuma solicitação aberta agora.', en: 'No open requests right now.', fr: 'Aucune demande ouverte pour le moment.' },
  { pt: 'Envie uma proposta com valor e mensagem claros.', en: 'Send a clear proposal with a price and message.', fr: 'Envoyez une proposition claire avec un prix et un message.' },
  { pt: 'Remover horário', en: 'Remove hours', fr: 'Supprimer l’horaire' },
  { pt: 'Nenhum bloqueio futuro.', en: 'No upcoming blocks.', fr: 'Aucun blocage à venir.' },
  { pt: 'Valores calculados a partir dos serviços retornados pela API.', en: 'Amounts calculated from the services returned by the API.', fr: 'Montants calculés à partir des services renvoyés par l’API.' },
  { pt: 'valores ainda não concluídos', en: 'amounts not completed yet', fr: 'montants pas encore finalisés' },
  { pt: 'Os valores resumem os serviços cadastrados e ajudam a acompanhar sua atividade profissional.', en: 'These values summarize registered services and help track professional activity.', fr: 'Ces valeurs récapitulent les services enregistrés et aident à suivre l’activité professionnelle.' },
  { pt: 'Atualize sua apresentação e os serviços oferecidos.', en: 'Update your introduction and offered services.', fr: 'Mettez à jour votre présentation et les services proposés.' },
  { pt: 'Preço de', en: 'Price for', fr: 'Prix pour' },
  { pt: 'Preço', en: 'Price', fr: 'Prix' },
  { pt: 'Habilitado para receber oportunidades na plataforma.', en: 'Enabled to receive opportunities on the platform.', fr: 'Autorisé à recevoir des opportunités sur la plateforme.' },
  { pt: 'Seus próximos atendimentos aparecerão aqui.', en: 'Your upcoming jobs will appear here.', fr: 'Vos prochaines interventions apparaîtront ici.' },
  { pt: 'Complete seus serviços e disponibilidade enquanto aguarda a análise da equipe.', en: 'Complete your services and availability while the team reviews your profile.', fr: 'Complétez vos services et disponibilités pendant l’examen de votre profil par l’équipe.' },
  { pt: 'abertas', en: 'open', fr: 'ouvertes' },
  { pt: 'Próximos atendimentos', en: 'Upcoming jobs', fr: 'Prochaines interventions' },
  { pt: 'Ver agenda', en: 'View schedule', fr: "Voir l’agenda" },
  { pt: 'Agenda livre', en: 'Schedule is clear', fr: 'Agenda libre' },
  { pt: 'Revisar perfil', en: 'Review profile', fr: 'Vérifier le profil' },
  { pt: 'Novas solicitações', en: 'New requests', fr: 'Nouvelles demandes' },
  { pt: 'Analisar', en: 'Review', fr: 'Examiner' },
  { pt: 'Organize sua semana', en: 'Organize your week', fr: 'Organisez votre semaine' },
  { pt: 'Salvar disponibilidade', en: 'Save availability', fr: 'Enregistrer les disponibilités' },
  { pt: 'Horários disponíveis', en: 'Available hours', fr: 'Horaires disponibles' },
  { pt: 'Adicionar horário', en: 'Add hours', fr: 'Ajouter un horaire' },
  { pt: 'Dia', en: 'Day', fr: 'Jour' },
  { pt: 'Início do horário', en: 'Start time', fr: 'Heure de début' },
  { pt: 'Fim', en: 'End', fr: 'Fin' },
  { pt: 'Bloqueios e exceções', en: 'Blocks and exceptions', fr: 'Blocages et exceptions' },
  { pt: 'Motivo', en: 'Reason', fr: 'Motif' },
  { pt: 'Adicionar bloqueio', en: 'Add block', fr: 'Ajouter un blocage' },
  { pt: 'Atendimentos', en: 'Jobs', fr: 'Interventions' },
  { pt: 'Estou a caminho', en: 'I am on the way', fr: 'Je suis en route' },
  { pt: 'Iniciar serviço', en: 'Start service', fr: 'Démarrer le service' },
  { pt: 'Concluir serviço', en: 'Complete service', fr: 'Terminer le service' },
  { pt: 'Sua vitrine', en: 'Your storefront', fr: 'Votre vitrine' },
  { pt: 'Apresentação', en: 'Introduction', fr: 'Présentation' },
  { pt: 'Título profissional', en: 'Professional title', fr: 'Titre professionnel' },
  { pt: 'Sobre você', en: 'About you', fr: 'À propos de vous' },
  { pt: 'Salvar perfil', en: 'Save profile', fr: 'Enregistrer le profil' },
  { pt: 'Defina preço e disponibilidade', en: 'Set price and availability', fr: 'Définissez le prix et les disponibilités' },
  { pt: 'Novo serviço', en: 'New service', fr: 'Nouveau service' },
  { pt: 'Adicionar serviço', en: 'Add service', fr: 'Ajouter un service' },
  { pt: 'Salvar', en: 'Save', fr: 'Enregistrer' },
  { pt: 'Remover', en: 'Remove', fr: 'Supprimer' },
  { pt: 'Novas oportunidades', en: 'New opportunities', fr: 'Nouvelles opportunités' },
  { pt: 'referência da plataforma', en: 'platform reference', fr: 'référence de la plateforme' },
  { pt: 'Quando', en: 'When', fr: 'Quand' },
  { pt: 'Duração', en: 'Duration', fr: 'Durée' },
  { pt: 'Área', en: 'Area', fr: 'Surface' },
  { pt: 'Não informada', en: 'Not provided', fr: 'Non indiquée' },
  { pt: 'Mensagem', en: 'Message', fr: 'Message' },
  { pt: 'Enviar proposta', en: 'Send proposal', fr: 'Envoyer la proposition' },
  { pt: 'Atividade profissional', en: 'Professional activity', fr: 'Activité professionnelle' },
  { pt: 'Serviços concluídos', en: 'Completed services', fr: 'Services terminés' },
  { pt: 'Serviços e valores', en: 'Services and amounts', fr: 'Services et montants' },
  { pt: 'Demonstração', en: 'Demo', fr: 'Démonstration' },
  { pt: 'Como usar estes valores', en: 'How to use these values', fr: 'Comment utiliser ces valeurs' },
  { pt: 'Centro de operações', en: 'Operations center', fr: "Centre d’opérations" },
  { pt: 'Indicadores e reservas recentes retornados pela API.', en: 'Metrics and recent bookings returned by the API.', fr: 'Indicateurs et réservations récentes renvoyés par l’API.' },
  { pt: 'Prestadores em análise', en: 'Providers under review', fr: 'Prestataires en cours d’examen' },
  { pt: 'confirmadas', en: 'confirmed', fr: 'confirmées' },
  { pt: 'cadastrados', en: 'registered', fr: 'inscrits' },
  { pt: 'Contas na plataforma', en: 'Accounts on the platform', fr: 'Comptes sur la plateforme' },
  { pt: 'Atualizado agora', en: 'Updated now', fr: 'Mis à jour maintenant' },
  { pt: 'Reservas recentes', en: 'Recent bookings', fr: 'Réservations récentes' },
  { pt: 'Sem atividade recente', en: 'No recent activity', fr: 'Aucune activité récente' },
  { pt: 'Buscar nos resultados carregados', en: 'Search loaded results', fr: 'Rechercher dans les résultats chargés' },
  { pt: 'Filtrar por status', en: 'Filter by status', fr: 'Filtrer par statut' },
  { pt: 'Todos os status', en: 'All statuses', fr: 'Tous les statuts' },
  { pt: 'Ativos e concluídos', en: 'Active and completed', fr: 'Actifs et terminés' },
  { pt: 'Pendentes', en: 'Pending', fr: 'En attente' },
  { pt: 'Atenção', en: 'Attention', fr: 'Attention' },
  { pt: 'Atualizar', en: 'Refresh', fr: 'Actualiser' },
  { pt: 'Dados indisponíveis', en: 'Data unavailable', fr: 'Données indisponibles' },
  { pt: 'Ajuste a busca ou remova os filtros.', en: 'Adjust the search or remove filters.', fr: 'Modifiez la recherche ou retirez les filtres.' },
  { pt: 'Justificativa', en: 'Reason', fr: 'Justification' },
  { pt: 'Confirmar ação', en: 'Confirm action', fr: "Confirmer l’action" },
  { pt: 'Repetir', en: 'Retry', fr: 'Réessayer' },
  { pt: 'Nenhum resultado', en: 'No results', fr: 'Aucun résultat' },
  { pt: 'Ocorreu um erro', en: 'Something went wrong', fr: 'Une erreur est survenue' },
  { pt: 'Sua rotina, simplificada', en: 'Your routine, simplified', fr: 'Votre quotidien, simplifié' },
  { pt: 'Da busca à contratação, você acompanha cada etapa com clareza.', en: 'From search to booking, follow every step with clarity.', fr: 'De la recherche à la réservation, suivez chaque étape avec clarté.' },
  { pt: 'Descreva sua necessidade', en: 'Describe what you need', fr: 'Décrivez votre besoin' },
  { pt: 'Escolha um serviço e conte os detalhes do espaço, endereço e melhor horário.', en: 'Choose a service and share the details, address and preferred time.', fr: 'Choisissez un service et précisez les détails, l’adresse et l’horaire souhaité.' },
  { pt: 'Compare profissionais', en: 'Compare professionals', fr: 'Comparez les professionnels' },
  { pt: 'Veja experiência, avaliações, preço inicial e disponibilidade antes de decidir.', en: 'Review experience, ratings, starting price and availability before deciding.', fr: 'Consultez l’expérience, les avis, le prix de départ et les disponibilités avant de décider.' },
  { pt: 'Confirme com segurança', en: 'Confirm securely', fr: 'Confirmez en toute sécurité' },
  { pt: 'Revise o valor de referência, confirme a reserva e receba a atualização pelo painel.', en: 'Review the reference value, confirm the booking and receive updates in your dashboard.', fr: 'Vérifiez la valeur de référence, confirmez la réservation et recevez les mises à jour dans votre tableau de bord.' },
  { pt: 'Converse e avalie', en: 'Message and review', fr: 'Échangez et laissez un avis' },
  { pt: 'Alinhe detalhes no chat e compartilhe sua experiência quando o serviço terminar.', en: 'Coordinate details in chat and share your experience when the service is complete.', fr: 'Coordonnez les détails dans le chat et partagez votre expérience une fois le service terminé.' },
  { pt: 'Confiança em cada etapa', en: 'Confidence at every step', fr: 'La confiance à chaque étape' },
  { pt: 'Segurança ChezVoust', en: 'ChezVoust safety', fr: 'Sécurité ChezVoust' },
  { pt: 'Camadas de proteção para clientes e profissionais usarem a plataforma com tranquilidade.', en: 'Layers of protection help customers and professionals use the platform with confidence.', fr: 'Plusieurs niveaux de protection permettent aux clients et aux professionnels d’utiliser la plateforme sereinement.' },
  { pt: 'A aprovação habilita o perfil na plataforma; não representa certificação documental ou de identidade.', en: 'Approval enables the profile on the platform; it is not document or identity certification.', fr: 'L’approbation active le profil sur la plateforme ; elle ne constitue pas une certification documentaire ou d’identité.' },
  { pt: 'O valor de referência e as regras de cancelamento são detalhados antes da confirmação.', en: 'The reference value and cancellation rules are shown before confirmation.', fr: 'La valeur de référence et les règles d’annulation sont détaillées avant la confirmation.' },
  { pt: 'Avaliações autênticas', en: 'Authentic reviews', fr: 'Avis authentiques' },
  { pt: 'Somente clientes com serviço concluído podem publicar uma avaliação.', en: 'Only customers with a completed service can publish a review.', fr: 'Seuls les clients dont le service est terminé peuvent publier un avis.' },
  { pt: 'Suporte e mediação', en: 'Support and mediation', fr: 'Assistance et médiation' },
  { pt: 'O módulo de chamados e disputas ainda não está integrado e permanece como requisito antes da operação comercial.', en: 'The support-ticket and dispute module is not integrated yet and remains required before commercial launch.', fr: 'Le module de demandes d’assistance et de litiges n’est pas encore intégré et reste requis avant le lancement commercial.' },
  { pt: 'Orientações da plataforma', en: 'Platform guidance', fr: 'Guide de la plateforme' },
  { pt: 'Veja o que já pode ser resolvido nesta versão e quais recursos ainda estão em evolução.', en: 'See what you can already do in this version and which features are still evolving.', fr: 'Découvrez ce qui est déjà disponible dans cette version et les fonctionnalités encore en évolution.' },
  { pt: 'Acompanhe detalhes, propostas e cancelamentos pelo painel. Reagendamento ainda não está disponível.', en: 'Track details, proposals and cancellations from your dashboard. Rescheduling is not available yet.', fr: 'Suivez les détails, propositions et annulations depuis votre tableau de bord. La reprogrammation n’est pas encore disponible.' },
  { pt: 'Valores e propostas', en: 'Values and proposals', fr: 'Valeurs et propositions' },
  { pt: 'Use os valores de referência e as propostas recebidas para combinar os detalhes diretamente com o profissional.', en: 'Use reference values and received proposals to arrange details directly with the professional.', fr: 'Utilisez les valeurs de référence et les propositions reçues pour convenir des détails directement avec le professionnel.' },
  { pt: 'Conta e segurança', en: 'Account and security', fr: 'Compte et sécurité' },
  { pt: 'Atualize dados pessoais, endereços e senha e consulte as notificações recebidas.', en: 'Update your personal information, addresses and password, and view received notifications.', fr: 'Mettez à jour vos informations personnelles, adresses et mot de passe, et consultez vos notifications.' },
  { pt: 'Chamados de suporte', en: 'Support requests', fr: 'Demandes d’assistance' },
  { pt: 'A abertura de chamados ainda não possui endpoint nem acompanhamento nesta versão.', en: 'Creating and tracking support requests is not available in this version yet.', fr: 'La création et le suivi des demandes d’assistance ne sont pas encore disponibles dans cette version.' },
  { pt: 'Transparência', en: 'Transparency', fr: 'Transparence' },
  { pt: 'Condições gerais para utilização da plataforma ChezVoust Pro.', en: 'General terms for using the ChezVoust Pro platform.', fr: 'Conditions générales d’utilisation de la plateforme ChezVoust Pro.' },
  { pt: 'Uso da plataforma', en: 'Platform use', fr: 'Utilisation de la plateforme' },
  { pt: 'A plataforma conecta clientes e profissionais e registra as etapas da contratação.', en: 'The platform connects customers and professionals and records each stage of the booking.', fr: 'La plateforme met en relation clients et professionnels et enregistre chaque étape de la réservation.' },
  { pt: 'Responsabilidades', en: 'Responsibilities', fr: 'Responsabilités' },
  { pt: 'Cada pessoa deve manter dados verdadeiros e respeitar as regras de convivência e segurança.', en: 'Everyone must provide accurate information and follow community and safety rules.', fr: 'Chaque personne doit fournir des informations exactes et respecter les règles de communauté et de sécurité.' },
  { pt: 'Valores e cancelamentos', en: 'Values and cancellations', fr: 'Valeurs et annulations' },
  { pt: 'Valores, taxas e regras aplicáveis são apresentados antes da confirmação da reserva.', en: 'Applicable prices, fees and rules are shown before the booking is confirmed.', fr: 'Les prix, frais et règles applicables sont présentés avant la confirmation de la réservation.' },
  { pt: 'Privacidade por padrão', en: 'Privacy by default', fr: 'Confidentialité par défaut' },
  { pt: 'Aviso de privacidade', en: 'Privacy notice', fr: 'Avis de confidentialité' },
  { pt: 'Como cuidamos dos dados necessários para operar a plataforma.', en: 'How we handle the data required to operate the platform.', fr: 'Comment nous traitons les données nécessaires au fonctionnement de la plateforme.' },
  { pt: 'Dados utilizados', en: 'Data we use', fr: 'Données utilisées' },
  { pt: 'Coletamos dados de conta, reserva, atendimento e segurança conforme a finalidade informada.', en: 'We collect account, booking, service and safety data for the stated purposes.', fr: 'Nous collectons les données de compte, de réservation, de service et de sécurité selon les finalités indiquées.' },
  { pt: 'Seus controles', en: 'Your controls', fr: 'Vos contrôles' },
  { pt: 'Correções de dados básicos estão disponíveis no perfil. Um canal operacional para acesso e exclusão deve ser configurado antes da produção.', en: 'Basic information can be corrected in your profile. An operational channel for access and deletion must be configured before production.', fr: 'Les informations de base peuvent être corrigées dans votre profil. Un canal opérationnel d’accès et de suppression doit être configuré avant la production.' },
  { pt: 'Proteção', en: 'Protection', fr: 'Protection' },
  { pt: 'Aplicamos controles técnicos e organizacionais compatíveis com o risco de cada operação.', en: 'We apply technical and organizational controls appropriate to the risk of each operation.', fr: 'Nous appliquons des mesures techniques et organisationnelles adaptées au risque de chaque opération.' },
  { pt: 'Cadastro profissional analisado', en: 'Professional profile reviewed', fr: 'Profil professionnel examiné' },
  { pt: 'Seu cadastro profissional foi atualizado para:', en: 'Your professional profile status was updated to:', fr: 'Le statut de votre profil professionnel a été mis à jour :' },
  { pt: 'Nova mensagem', en: 'New message', fr: 'Nouveau message' },
  { pt: 'enviou uma mensagem.', en: 'sent a message.', fr: 'a envoyé un message.' },
  { pt: 'Nova avaliação', en: 'New review', fr: 'Nouvel avis' },
  { pt: 'Você recebeu uma nova avaliação.', en: 'You received a new review.', fr: 'Vous avez reçu un nouvel avis.' },
  { pt: 'Nova proposta', en: 'New proposal', fr: 'Nouvelle proposition' },
  { pt: 'Um profissional enviou uma proposta para seu serviço.', en: 'A professional sent a proposal for your service.', fr: 'Un professionnel a envoyé une proposition pour votre service.' },
  { pt: 'Reserva confirmada', en: 'Booking confirmed', fr: 'Réservation confirmée' },
  { pt: 'O horário foi reservado e a reserva está confirmada.', en: 'The time slot was reserved and the booking is confirmed.', fr: 'Le créneau a été réservé et la réservation est confirmée.' },
  { pt: 'Sua reserva foi confirmada.', en: 'Your booking was confirmed.', fr: 'Votre réservation a été confirmée.' },
  { pt: 'Nova reserva em andamento', en: 'New booking in progress', fr: 'Nouvelle réservation en cours' },
  { pt: 'Um cliente iniciou uma reserva com você.', en: 'A customer started a booking with you.', fr: 'Un client a commencé une réservation avec vous.' },
  { pt: 'Proposta aceita', en: 'Proposal accepted', fr: 'Proposition acceptée' },
  { pt: 'O cliente aceitou sua proposta.', en: 'The customer accepted your proposal.', fr: 'Le client a accepté votre proposition.' },
  { pt: 'Reserva cancelada', en: 'Booking cancelled', fr: 'Réservation annulée' },
  { pt: 'A reserva foi cancelada.', en: 'The booking was cancelled.', fr: 'La réservation a été annulée.' },
  { pt: 'Reserva reagendada', en: 'Booking rescheduled', fr: 'Réservation reprogrammée' },
  { pt: 'Serviço concluído', en: 'Service completed', fr: 'Service terminé' },
  { pt: 'Serviço iniciado', en: 'Service started', fr: 'Service démarré' },
  { pt: 'Reserva', en: 'Booking', fr: 'Réservation' },
  { pt: 'O cliente escolheu um novo horário.', en: 'The customer chose a new time.', fr: 'Le client a choisi un nouvel horaire.' },
  { pt: 'A situação da sua reserva foi atualizada.', en: 'Your booking status was updated.', fr: 'Le statut de votre réservation a été mis à jour.' },
  { pt: 'Profissional a definir', en: 'Professional to be assigned', fr: 'Professionnel à attribuer' },
  { pt: 'avaliações', en: 'reviews', fr: 'avis' },
  { pt: 'Operação', en: 'Operations', fr: 'Opérations' },
  { pt: 'Acompanhe o ciclo das reservas retornadas pela API.', en: 'Track the lifecycle of bookings returned by the API.', fr: 'Suivez le cycle des réservations renvoyées par l’API.' },
  { pt: 'Comunidade', en: 'Community', fr: 'Communauté' },
  { pt: 'Gerencie o estado das contas de clientes.', en: 'Manage customer account status.', fr: 'Gérez le statut des comptes clients.' },
  { pt: 'Rede profissional', en: 'Professional network', fr: 'Réseau professionnel' },
  { pt: 'Prestadores pendentes', en: 'Pending providers', fr: 'Prestataires en attente' },
  { pt: 'Aprove ou rejeite perfis que aguardam análise.', en: 'Approve or reject profiles awaiting review.', fr: 'Approuvez ou refusez les profils en attente d’examen.' },
  { pt: 'Oferta da plataforma', en: 'Platform offering', fr: 'Offre de la plateforme' },
  { pt: 'Consulte serviços e preços-base publicados.', en: 'View published services and base prices.', fr: 'Consultez les services publiés et leurs prix de base.' },
  { pt: 'Promoções', en: 'Promotions', fr: 'Promotions' },
  { pt: 'Prévia visual: a API atual não expõe chamados de suporte.', en: 'Visual preview: the current API does not expose support requests.', fr: 'Aperçu visuel : l’API actuelle n’expose pas les demandes d’assistance.' },
  { pt: 'Prévia visual: a API atual não expõe configurações administrativas.', en: 'Visual preview: the current API does not expose administrative settings.', fr: 'Aperçu visuel : l’API actuelle n’expose pas les paramètres administratifs.' },
  { pt: 'Cliente / Profissional', en: 'Customer / Professional', fr: 'Client / Professionnel' },
  { pt: 'Cliente / profissional', en: 'Customer / professional', fr: 'Client / professionnel' },
  { pt: 'Contato', en: 'Contact', fr: 'Contact' },
  { pt: 'Cadastro', en: 'Registration', fr: 'Inscription' },
  { pt: 'Papel', en: 'Role', fr: 'Rôle' },
  { pt: 'Local', en: 'Location', fr: 'Lieu' },
  { pt: 'Categoria', en: 'Category', fr: 'Catégorie' },
  { pt: 'Preço-base', en: 'Base price', fr: 'Prix de base' },
  { pt: 'Precificação', en: 'Pricing', fr: 'Tarification' },
  { pt: 'Criação', en: 'Created', fr: 'Création' },
  { pt: 'Uso', en: 'Usage', fr: 'Utilisation' },
  { pt: 'Vigência', en: 'Validity', fr: 'Validité' },
  { pt: 'Recurso', en: 'Feature', fr: 'Fonctionnalité' },
  { pt: 'Estado', en: 'State', fr: 'État' },
  { pt: 'Origem', en: 'Source', fr: 'Origine' },
  { pt: 'Observação', en: 'Note', fr: 'Observation' },
  { pt: 'Configuração', en: 'Setting', fr: 'Paramètre' },
  { pt: 'Escopo', en: 'Scope', fr: 'Portée' },
  { pt: 'Adicionar serviço ao catálogo', en: 'Add a service to the catalog', fr: 'Ajouter un service au catalogue' },
  { pt: 'Modelo de preço', en: 'Pricing method', fr: 'Mode de tarification' },
  { pt: 'Valor fixo', en: 'Fixed price', fr: 'Prix fixe' },
  { pt: 'Por hora', en: 'Per hour', fr: 'Par heure' },
  { pt: 'Por m²', en: 'Per m²', fr: 'Par m²' },
  { pt: 'Duração padrão', en: 'Default duration', fr: 'Durée par défaut' },
  { pt: 'Descrição curta', en: 'Short description', fr: 'Description courte' },
  { pt: 'Criar serviço', en: 'Create service', fr: 'Créer le service' },
  { pt: 'Código', en: 'Code', fr: 'Code' },
  { pt: 'Tipo', en: 'Type', fr: 'Type' },
  { pt: 'Percentual', en: 'Percentage', fr: 'Pourcentage' },
  { pt: 'Pedido mínimo', en: 'Minimum order', fr: 'Commande minimale' },
  { pt: 'Limite de usos', en: 'Usage limit', fr: 'Limite d’utilisation' },
  { pt: 'Funcionalidade não integrada', en: 'Feature not integrated', fr: 'Fonctionnalité non intégrée' },
  { pt: 'Dados demonstrativos', en: 'Demo data', fr: 'Données de démonstration' },
  { pt: 'Sem endpoint', en: 'No endpoint', fr: 'Aucun endpoint' },
  { pt: 'Nenhuma ação disponível', en: 'No action available', fr: 'Aucune action disponible' },
  { pt: 'Aprovar', en: 'Approve', fr: 'Approuver' },
  { pt: 'Rejeitar', en: 'Reject', fr: 'Refuser' },
  { pt: 'Ativar', en: 'Activate', fr: 'Activer' },
  { pt: 'Suspender', en: 'Suspend', fr: 'Suspendre' },
  { pt: 'Anterior', en: 'Previous', fr: 'Précédent' },
  { pt: 'Próxima', en: 'Next', fr: 'Suivant' },
  { pt: 'Carregando', en: 'Loading', fr: 'Chargement' }
];

// A ordem é invariável. Calculá-la uma única vez evita uma ordenação para cada
// nó de texto observado pela camada de localização.
const ORDERED_TRANSLATIONS = [...TRANSLATIONS].sort((left, right) => right.pt.length - left.pt.length);

@Injectable({ providedIn: 'root' })
export class LocalizationService {
  private readonly document = inject(DOCUMENT);
  readonly language = signal<AppLanguage>(this.readLanguage());
  readonly currency = signal<AppCurrency>(this.readCurrency());
  readonly locale = computed(() => this.language() === 'fr' ? 'fr-FR' : this.language() === 'en' ? 'en-US' : 'pt-BR');

  constructor() {
    this.applyDocumentLanguage(this.language());
  }

  setLanguage(language: string): void {
    if (language !== 'pt' && language !== 'en' && language !== 'fr') return;
    this.language.set(language);
    this.safeStore(LANGUAGE_KEY, language);
    this.applyDocumentLanguage(language);
  }

  setCurrency(currency: string): void {
    if (currency !== 'BRL' && currency !== 'EUR' && currency !== 'USD') return;
    this.currency.set(currency);
    this.safeStore(CURRENCY_KEY, currency);
  }

  translate(source: string): string {
    if (!source || !source.trim()) return source;
    const language = this.language();
    // O conteúdo-fonte é português. Não aplique padrões de inglês quando a
    // preferência também é português; isso transformava títulos dinâmicos em
    // textos híbridos, como "Professionals for sua casa".
    if (language === 'pt') return source;
    const leading = source.match(/^\s*/)?.[0] ?? '';
    const trailing = source.match(/\s*$/)?.[0] ?? '';
    const value = source.trim();
    const exact = TRANSLATIONS.find((entry) => entry.pt === value || entry.en === value || entry.fr === value);
    if (exact) return `${leading}${exact[language]}${trailing}`;

    const sourceLanguage: 'pt' | 'en' = ORDERED_TRANSLATIONS.some((entry) => value.includes(entry.pt)) ? 'pt' : 'en';
    // Frases com variáveis ("5 profissionais", por exemplo) precisam ser
    // resolvidas antes de traduzir palavras isoladas; caso contrário sobra
    // uma interface híbrida como "Professionals for sua casa".
    let translated = this.translatePatterns(value, language);
    for (const entry of ORDERED_TRANSLATIONS) {
      const target = entry[language];
      const sourceValue = entry[sourceLanguage];
      if (sourceValue && translated.includes(sourceValue)) translated = translated.split(sourceValue).join(target);
    }
    return `${leading}${translated}${trailing}`;
  }

  formatMoney(amount: number, sourceCurrency: AppCurrency = 'BRL', maximumFractionDigits = 2): string {
    if (!Number.isFinite(amount)) return '—';
    const target = this.currency();
    const converted = this.convertAmount(amount, sourceCurrency, target);
    return new Intl.NumberFormat(this.locale(), {
      style: 'currency', currency: target, minimumFractionDigits: 0, maximumFractionDigits
    }).format(converted);
  }

  convertAmount(amount: number, sourceCurrency: AppCurrency, targetCurrency: AppCurrency = this.currency()): number {
    if (!Number.isFinite(amount) || sourceCurrency === targetCurrency) return amount;
    const toBrl = (value: number, currency: AppCurrency): number => currency === 'USD'
      ? value / USD_PER_BRL
      : currency === 'EUR' ? value / EUR_PER_BRL : value;
    const fromBrl = (value: number, currency: AppCurrency): number => currency === 'USD'
      ? value * USD_PER_BRL
      : currency === 'EUR' ? value * EUR_PER_BRL : value;
    return fromBrl(toBrl(amount, sourceCurrency), targetCurrency);
  }

  private translatePatterns(value: string, language: AppLanguage): string {
    const replacements: Array<[RegExp, string]> = language === 'fr' ? [
      [/Mostrando (\d+) de (\d+) registros · página (\d+) de (\d+)/g, 'Affichage de $1 sur $2 résultats · page $3 sur $4'],
      [/(\d+) serviços disponíveis/g, '$1 services disponibles'],
      [/(\d+) serviços/g, '$1 services'],
      [/(\d+) profissionais/g, '$1 professionnels'],
      [/(\d+) opções/g, '$1 options'],
      [/(\d+) opção/g, '$1 option'],
      [/Abrir painel de (.+)/g, 'Ouvrir le tableau de bord de $1'],
      [/Profissionais para (.+)/g, 'Professionnels pour $1'],
      [/A partir de (.+)/g, 'À partir de $1']
    ] : [
      [/Mostrando (\d+) de (\d+) registros · página (\d+) de (\d+)/g, 'Showing $1 of $2 results · page $3 of $4'],
      [/(\d+) serviços disponíveis/g, '$1 services available'],
      [/(\d+) serviços/g, '$1 services'],
      [/(\d+) profissionais/g, '$1 professionals'],
      [/(\d+) opções/g, '$1 options'],
      [/(\d+) opção/g, '$1 option'],
      [/Abrir painel de (.+)/g, "Open $1's dashboard"],
      [/Profissionais para (.+)/g, 'Professionals for $1'],
      [/A partir de (.+)/g, 'From $1']
    ];
    return replacements.reduce((result, [pattern, replacement]) => result.replace(pattern, replacement), value);
  }

  private readLanguage(): AppLanguage {
    try { const stored = localStorage.getItem(LANGUAGE_KEY); return stored === 'en' || stored === 'fr' || stored === 'pt' ? stored : 'pt'; } catch { return 'pt'; }
  }

  private readCurrency(): AppCurrency {
    try {
      const stored = localStorage.getItem(CURRENCY_KEY);
      return stored === 'USD' || stored === 'EUR' || stored === 'BRL' ? stored : 'BRL';
    } catch { return 'BRL'; }
  }

  private safeStore(key: string, value: string): void {
    try { localStorage.setItem(key, value); } catch { /* Storage may be unavailable in privacy-restricted contexts. */ }
  }

  private applyDocumentLanguage(language: AppLanguage): void {
    this.document.documentElement.lang = language === 'pt' ? 'pt-BR' : language === 'fr' ? 'fr-FR' : 'en-US';
  }
}
